// ============================================================
// CaveScene.js  —  Cave Level 1: "The Tunnels"
// Entered from the cave entrance in GameScene.
// Reuses player textures and DialogueBox from the main game.
// State persists via window.gameState.
// ============================================================

class CaveScene extends Phaser.Scene {

    constructor() { super({ key: 'CaveScene' }); }

    create() {
        const W = 800, H = 560;
        this.physics.world.setBounds(0, 0, W, H);

        this._actionWasPressed = false;
        this._walkFrame  = 0;
        this._walkTimer  = 0;
        this._footTimer  = 0;
        this._returning  = false;

        // ---- World ----
        this._drawCave(W, H);

        // ---- Obstacles ----
        this.obstacles = this.physics.add.staticGroup();
        this._buildWalls(W, H);

        // ---- Player ----
        this.player = this.physics.add.sprite(400, 450, 'player_idle');
        this.player.setCollideWorldBounds(true).setDepth(10);
        this.physics.add.collider(this.player, this.obstacles);

        // ---- Camera ----
        this.cameras.main.setBounds(0, 0, W, H);
        this.cameras.main.startFollow(this.player, true, 0.1, 0.1);
        this.cameras.main.fadeIn(1200, 0, 0, 0);

        // ---- UI ----
        this.dialogue = new DialogueBox(this);

        this.interactHint = this.add.text(0, 0, '', {
            fontSize: '9px', fill: '#ccffcc', fontFamily: 'monospace',
            backgroundColor: '#000000cc', padding: { x: 5, y: 3 }
        }).setDepth(50).setVisible(false);

        // ---- Content ----
        this._createAtmosphere();
        this._createCrystalRoom();
        this._buildInteractables();

        // ---- Input ----
        this.cursors = this.input.keyboard.createCursorKeys();
        this.wasd    = this.input.keyboard.addKeys({
            up: Phaser.Input.Keyboard.KeyCodes.W, down: Phaser.Input.Keyboard.KeyCodes.S,
            left: Phaser.Input.Keyboard.KeyCodes.A, right: Phaser.Input.Keyboard.KeyCodes.D
        });
        this.eKey = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.E);

        // ---- Player light (drawn every frame in update) ----
        this._playerLight = this.add.graphics().setDepth(9);

        // ---- Cave depth label ----
        this.add.text(400, 12, 'THE TUNNELS  —  LEVEL 1', {
            fontSize: '8px', fill: '#44664444', fontFamily: 'monospace'
        }).setScrollFactor(0).setDepth(20).setOrigin(0.5, 0);
    }

    // ----------------------------------------------------------
    update() {
        if (this.dialogue.isVisible()) {
            this.player.setVelocity(0, 0);
            const down = this.eKey.isDown || window.virtualKeys.action;
            if (down && !this._actionWasPressed) { this._actionWasPressed = true; this.dialogue.tryDismiss(); }
            if (!down) this._actionWasPressed = false;
            return;
        }

        const spd = 140;
        const goU = this.cursors.up.isDown    || this.wasd.up.isDown    || window.virtualKeys.up;
        const goD = this.cursors.down.isDown  || this.wasd.down.isDown  || window.virtualKeys.down;
        const goL = this.cursors.left.isDown  || this.wasd.left.isDown  || window.virtualKeys.left;
        const goR = this.cursors.right.isDown || this.wasd.right.isDown || window.virtualKeys.right;

        let vx = 0, vy = 0;
        if (goL) vx = -spd;  if (goR) vx = spd;
        if (goU) vy = -spd;  if (goD) vy = spd;
        if (vx && vy) { vx *= 0.707; vy *= 0.707; }
        this.player.setVelocity(vx, vy);

        // Walk animation (reuses textures generated by GameScene)
        if (vx || vy) {
            this._walkTimer -= 16;
            if (this._walkTimer <= 0) { this._walkTimer = 180; this._walkFrame ^= 1; }
            const tex = (vy < 0 && !vx) ? 'player_back'
                : (this._walkFrame ? 'player_walkA' : 'player_walkB');
            this.player.setTexture(tex);
            if (vx < 0) this.player.setFlipX(true);
            else if (vx > 0) this.player.setFlipX(false);
        } else {
            this.player.setTexture('player_idle');
            this._walkFrame = 0; this._walkTimer = 0;
        }

        // Footsteps
        if (vx || vy) {
            this._footTimer -= 16;
            if (this._footTimer <= 0) {
                this._footTimer = 360;
                if (window.soundManager && window.soundManager.ready) window.soundManager.playFootstep();
            }
        } else { this._footTimer = 0; }

        // Player light — warm candle-like glow (redrawn every frame to follow player)
        this._playerLight.clear();
        this._playerLight.fillStyle(0xffe8a0, 0.18); this._playerLight.fillCircle(this.player.x, this.player.y, 110);
        this._playerLight.fillStyle(0xffd060, 0.10); this._playerLight.fillCircle(this.player.x, this.player.y, 170);

        // Interact hint
        const near = this._nearest();
        if (near) {
            this.interactHint.setText('[ E ]  ' + near.label);
            this.interactHint.setPosition(near.x - this.interactHint.width / 2, near.y - 44);
            this.interactHint.setVisible(true);
        } else { this.interactHint.setVisible(false); }

        // Action press
        const down = this.eKey.isDown || window.virtualKeys.action;
        if (down && !this._actionWasPressed) {
            this._actionWasPressed = true;
            if (near) this._interact(near);
        }
        if (!down) this._actionWasPressed = false;

        // Exit trigger — bottom of entry shaft
        if (!this._returning && this.player.y > 496 && this.player.x > 348 && this.player.x < 452) {
            this._returnSurface();
        }
    }

    // ----------------------------------------------------------
    _nearest() {
        let best = null, bd = Infinity;
        for (const o of this._objs) {
            if (o.done) continue;
            const d = Phaser.Math.Distance.Between(this.player.x, this.player.y, o.x, o.y);
            if (d <= o.range && d < bd) { bd = d; best = o; }
        }
        return best;
    }

    _interact(obj) {
        const txt = typeof obj.text === 'function' ? obj.text() : obj.text;
        if (!txt) return;
        if (window.soundManager && window.soundManager.ready) window.soundManager.playInteract();
        this.dialogue.show(obj.speaker || '', txt, () => { if (obj.after) obj.after(this); });
    }

    // ----------------------------------------------------------
    _drawCave(W, H) {
        // Background — solid bedrock
        this.add.rectangle(W / 2, H / 2, W, H, 0x060504);

        const g = this.add.graphics().setDepth(1);

        // Entry shaft floor
        g.fillStyle(0x18120e); g.fillRect(348, 440, 104, 120);

        // Main chamber floor — earthy
        g.fillStyle(0x1e1812); g.fillRect(60, 160, 680, 300);

        // Crystal alcove floor — teal tinted
        g.fillStyle(0x0c1a18); g.fillRect(560, 30, 200, 145);

        // Rocky wall texture strips
        g.fillStyle(0x100e0c);
        g.fillRect(0, 0, 60, H);      // left rock
        g.fillRect(740, 0, 60, H);    // right rock
        g.fillRect(0, 0, W, 30);      // top rock
        g.fillRect(0, 440, 348, 120); // bottom-left (sides of entry shaft)
        g.fillRect(452, 440, W-452, 120); // bottom-right
        g.fillRect(0, 140, 560, 30);  // ceiling left of crystal passage

        // Ceiling passage marker (rock arch over crystal alcove entrance)
        g.fillStyle(0x0e0c0a);
        g.fillRect(740, 30, 20, 145); // right side of crystal room wall stub

        // Puddles (dark reflective)
        g.fillStyle(0x0a1820, 0.7);
        [[160,360,70,22],[500,430,90,25],[320,220,55,18],[640,280,50,16]].forEach(([x,y,w,h]) => g.fillEllipse(x,y,w,h));

        // Root tendrils from ceiling
        g.lineStyle(1, 0x2a1a08, 0.5);
        [[120,165,106,215],[250,162,238,208],[380,163,366,230],
         [520,164,510,202],[680,162,672,205],[200,162,192,240]].forEach(([x1,y1,x2,y2]) => {
            g.beginPath(); g.moveTo(x1,y1); g.lineTo(x2,y2); g.strokePath();
        });

        // Crack lines in floor
        g.lineStyle(1, 0x2a2010, 0.25);
        [[100,220,200,260],[380,340,440,310],[560,400,630,380]].forEach(([x1,y1,x2,y2]) => g.lineBetween(x1,y1,x2,y2));

        // Glowing mushroom clusters
        [[175,380,0xbb5500],[210,260,0xcc6600],[560,420,0xaa4400],[660,360,0xcc5500],[420,340,0xbb5000]].forEach(([x,y,col]) => {
            g.fillStyle(col, 0.5); g.fillCircle(x, y, 6);
            g.fillStyle(col, 0.25); g.fillCircle(x, y, 12);
        });

        // Sealed area hint — metal panels along ceiling (drawn as dark gray rectangles)
        g.fillStyle(0x1a2020); g.fillRect(210, 32, 300, 90); // old research console
        g.lineStyle(1, 0x2a3030); g.strokeRect(210, 32, 300, 90);
        g.fillStyle(0x0a1212); g.fillRect(220, 40, 100, 50); // screen
        g.fillStyle(0x001400); g.fillRect(222, 42, 96, 46);  // dark CRT
        g.lineStyle(1, 0x002200, 0.4);
        for (let ly = 46; ly < 86; ly += 6) g.lineBetween(222, ly, 318, ly); // scan lines
        g.fillStyle(0x001100, 0.3); g.fillCircle(320, 88, 4); // dead status light
        g.lineStyle(1, 0x334433);
        g.lineBetween(330, 50, 340, 45); g.lineBetween(340, 60, 352, 55); // knobs

        // SECTOR 7 sealed door — embedded in the ceiling wall at y≈150
        g.fillStyle(0x1c2828); g.fillRect(350, 130, 104, 32);   // door frame
        g.fillStyle(0x141e1e); g.fillRect(354, 133, 96, 26);    // door face
        g.lineStyle(1, 0x2a3838); g.strokeRect(354, 133, 96, 26);
        g.fillStyle(0x243030); g.fillRect(397, 140, 10, 12);    // handle recess
        g.fillStyle(0x0a1414); g.fillRect(399, 141, 6, 10);     // keypad dead
        g.fillStyle(0x550000, 0.7); g.fillCircle(402, 146, 2);  // dead red light
        this.add.text(400, 136, 'SECTOR 7', {
            fontSize: '5px', fill: '#2a4444', fontFamily: 'monospace'
        }).setDepth(5).setOrigin(0.5, 0);

        // Ventilation shaft grate (to the left of the door, at ceiling wall)
        g.fillStyle(0x1a2424); g.fillRect(318, 134, 22, 24);    // shaft frame
        g.lineStyle(1, 0x2a3434, 0.8);
        for (let ly = 136; ly < 156; ly += 5) g.lineBetween(320, ly, 338, ly); // grate bars
        g.lineBetween(329, 134, 329, 158); // vertical bar

        // Entry shaft visual (dark shaft going down)
        g.fillStyle(0x0a0806); g.fillRect(348, 480, 104, 80);
        g.lineStyle(1, 0x3a2a1a, 0.4);
        g.lineBetween(348, 450, 348, 560); g.lineBetween(452, 450, 452, 560);
        this.add.text(400, 472, '▲ SURFACE', {
            fontSize: '7px', fill: '#554433', fontFamily: 'monospace'
        }).setDepth(5).setOrigin(0.5);
    }

    _createAtmosphere() {
        // Drip particles
        const drips = [];
        [[200,164],[420,163],[580,164],[700,163]].forEach(([dx, dy]) => {
            const d = this.add.graphics().setDepth(6);
            drips.push({ g: d, x: dx, y: dy, speed: 0.4 + Math.random() * 0.4 });
        });
        this.time.addEvent({
            delay: 60, loop: true, callback: () => {
                drips.forEach(d => {
                    d.y += d.speed * 2;
                    d.g.clear();
                    if (d.y < 420) {
                        d.g.fillStyle(0x2a4a5a, 0.7); d.g.fillEllipse(d.x, d.y, 3, 5);
                    }
                    if (d.y > 430 + Math.random() * 30) {
                        d.y = 163 + Math.random() * 4;
                        d.x += (Math.random() - 0.5) * 8;
                    }
                });
            }
        });

        // Mushroom pulse tweens
        [[175,380],[210,260],[420,340]].forEach(([mx, my]) => {
            const mg = this.add.graphics().setDepth(3);
            mg.fillStyle(0xff6600, 0.08); mg.fillCircle(mx, my, 22);
            this.tweens.add({ targets: mg, alpha: {from: 0.3, to: 1}, yoyo: true, repeat: -1, duration: 1200 + mx % 500 });
        });
    }

    _createCrystalRoom() {
        const g = this.add.graphics().setDepth(4);
        // Crystal spires
        const spires = [
            [580,130,30],[608,100,40],[636,118,28],[664,90,45],[692,112,32],[718,98,38],[738,125,24]
        ];
        spires.forEach(([cx, cy, h]) => {
            g.fillStyle(0x00bbaa, 0.75);
            g.fillTriangle(cx - 9, cy, cx, cy - h, cx + 9, cy);
            g.fillStyle(0x00ffee, 0.45);
            g.fillTriangle(cx - 3, cy, cx, cy - h + 8, cx + 3, cy);
        });

        // Ambient teal glow
        const glow = this.add.graphics().setDepth(2);
        glow.fillStyle(0x00ccbb, 0.1); glow.fillRect(560, 30, 200, 145);
        this.tweens.add({ targets: glow, alpha: {from: 0.3, to: 0.9}, yoyo: true, repeat: -1, duration: 1800 });

        // One loose shard on the ground
        this._crystalShard = this.add.graphics().setDepth(5);
        this._crystalShard.fillStyle(0x00ffee, 0.8); this._crystalShard.fillTriangle(664, 148, 659, 134, 669, 134);
        this._crystalShard.fillStyle(0xaaffff, 0.5); this._crystalShard.fillTriangle(662, 147, 664, 136, 666, 147);
        this.tweens.add({ targets: this._crystalShard, alpha: {from: 0.6, to: 1}, yoyo: true, repeat: -1, duration: 700 });

        // Hide shard if already collected
        if (window.gameState && window.gameState.collected && window.gameState.collected.includes('cave_crystal_shard')) {
            this._crystalShard.setVisible(false);
        }
    }

    _buildInteractables() {
        this._objs = [
            {
                id: 'backpack', x: 220, y: 375, range: 62, label: 'Examine backpack',
                speaker: 'BACKPACK',
                text: '"PROPERTY OF PINEBROOK NUCLEAR RESERVE\nFIELD SURVEY UNIT 3"\n\nInside: a waterlogged notebook. One page still readable:\n"Day 3. Crystal formations too geometrical.\nNot natural. Unit chief says don\'t ask questions.\nSomebody excavated these tunnels on purpose."'
            },
            {
                id: 'fire_ring', x: 418, y: 418, range: 62, label: 'Examine fire ring',
                speaker: '',
                text: 'A stone fire ring. The charcoal is cold but not ancient.\nSomebody has been sleeping down here.\nA flattened sleeping area in the dirt next to it.\n\nRecently.'
            },
            {
                id: 'research_console', x: 358, y: 88, range: 70, label: 'Examine console',
                speaker: 'TERMINAL',
                text: '[NO POWER]\n\nA research terminal. The casing reads:\n"EMBERLIGHT FIELD STATION B-7"\n\nA handwritten note taped to the screen:\n"If power fails — fall back to Site B.\nDO NOT use north tunnel. — M.C."'
            },
            {
                id: 'crystal_shard', x: 664, y: 140, range: 65, label: 'Examine crystals',
                speaker: '',
                text: () => {
                    const col = window.gameState && window.gameState.collected ? window.gameState.collected : [];
                    return col.includes('cave_crystal_shard')
                        ? 'The crystal formations pulse faintly. Cold and symmetrical.\nDefinitely not natural.'
                        : 'Incredible formations — teal, geometric, cold to the touch.\nOne shard has worked loose. It\'s warm, almost alive.\n\n[You could take it]';
                },
                after: (s) => {
                    if (!window.gameState) return;
                    const col = window.gameState.collected || [];
                    if (!col.includes('cave_crystal_shard')) {
                        col.push('cave_crystal_shard');
                        window.gameState.collected = col;
                        window.gameState.artifactCounts = window.gameState.artifactCounts || {arrowheads:0,pottery:0,tools:0};
                        window.gameState.artifactCounts.pottery =
                            (window.gameState.artifactCounts.pottery || 0) + 1;
                        if (s._crystalShard) s._crystalShard.setVisible(false);
                        s.dialogue.show('', 'You pocketed the crystal shard.\nIt hums faintly in your hand.\n\n[Bonus artifact — Frank will want to see this]');
                    }
                }
            },
            {
                id: 'sealed_door', x: 400, y: 180, range: 72, label: 'Examine sealed door',
                speaker: '',
                text: () => {
                    const col = (window.gameState && window.gameState.collected) || [];
                    if (col.includes('facility_log'))
                        return 'You\'ve already been inside.\n\nDr. Chen\'s log is saved.\nSomeone needs to see this.';
                    if (col.includes('frank_lore_3'))
                        return 'The door is sealed — but beside it, almost hidden by years of mineral growth, a ventilation shaft cover.\nLoose. Corroded.\n\nYou pull it free.\n\n[ You squeeze through into the darkness. ]';
                    return 'A heavy steel door set into the rock.\n"SECTOR 7 — AUTHORIZED PERSONNEL ONLY"\n\nBolted from inside. No power to the keypad.\nSomething important enough to seal permanently.\n\nNot yet. Come back when you know more.';
                },
                after: (s) => {
                    const col = (window.gameState && window.gameState.collected) || [];
                    if (col.includes('frank_lore_3') && !col.includes('facility_log')) {
                        s.cameras.main.fade(900, 0, 0, 0);
                        s.time.delayedCall(1000, () => s.scene.start('Sector7Scene'));
                    }
                }
            },
            {
                id: 'exit', x: 400, y: 486, range: 58, label: 'Return to surface',
                speaker: '',
                text: 'The entry shaft. Daylight above.\nYou could head back to the campground.',
                after: (s) => s._returnSurface()
            }
        ];
    }

    _buildWalls(W, H) {
        const add = (x, y, w, h) => {
            const b = this.obstacles.create(x, y, 'pixel');
            b.setVisible(false); b.setDisplaySize(w, h); b.body.setSize(w, h); b.refreshBody();
        };
        add(W/2, 15, W, 30);           // top border
        add(30, H/2, 60, H);           // left border
        add(770, H/2, 60, H);          // right border
        add(174, 500, 348, 120);        // bottom-left (beside entry shaft)
        add(626, 500, 348, 120);        // bottom-right
        add(275, 150, 550, 22);         // ceiling left (blocks sealed area)
        // Ceiling gap is at x:550-740 → crystal alcove passage is open there
        // Small ceiling stub right of crystal alcove
        add(750, 85, 20, 130);          // prevents slipping past right edge
    }

    _returnSurface() {
        if (this._returning) return;
        this._returning = true;
        this.cameras.main.fade(1000, 0, 0, 0);
        this.time.delayedCall(1100, () => this.scene.start('GameScene'));
    }
}
